kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-ca
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    linkerd.io/created-by: linkerd/cli stable-2.2.1
  labels:
    linkerd.io/control-plane-component: ca
  name: linkerd-ca
  namespace: kube-system
spec:
  selector:
    matchLabels:
      linkerd.io/control-plane-component: ca
  replicas: 1
  template:
    metadata:
      annotations:
        linkerd.io/created-by: linkerd/cli stable-2.2.1
        linkerd.io/proxy-version: stable-2.2.1
      labels:
        linkerd.io/control-plane-component: ca
        linkerd.io/control-plane-ns: kube-system
        linkerd.io/proxy-deployment: linkerd-ca
    spec:
      containers:
        - args:
            - ca
            - -controller-namespace=kube-system
            - -single-namespace=false
            - -log-level=info
          image: gcr.io/linkerd-io/controller:stable-2.2.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /ping
              port: 9997
            initialDelaySeconds: 10
          name: ca
          ports:
            - containerPort: 9997
              name: admin-http
          readinessProbe:
            failureThreshold: 7
            httpGet:
              path: /ready
              port: 9997
          resources:
            requests:
              cpu: 20m
              memory: 50Mi
          securityContext:
            runAsUser: 2103
        - env:
            - name: LINKERD2_PROXY_LOG
              value: warn,linkerd2_proxy=info
            - name: LINKERD2_PROXY_CONTROL_URL
              value: tcp://linkerd-proxy-api.kube-system.svc.cluster.local:8086
            - name: LINKERD2_PROXY_CONTROL_LISTENER
              value: tcp://0.0.0.0:4190
            - name: LINKERD2_PROXY_METRICS_LISTENER
              value: tcp://0.0.0.0:4191
            - name: LINKERD2_PROXY_OUTBOUND_LISTENER
              value: tcp://127.0.0.1:4140
            - name: LINKERD2_PROXY_INBOUND_LISTENER
              value: tcp://0.0.0.0:4143
            - name: LINKERD2_PROXY_DESTINATION_PROFILE_SUFFIXES
              value: .
            - name: LINKERD2_PROXY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LINKERD2_PROXY_INBOUND_ACCEPT_KEEPALIVE
              value: 10000ms
            - name: LINKERD2_PROXY_OUTBOUND_CONNECT_KEEPALIVE
              value: 10000ms
            - name: LINKERD2_PROXY_ID
              value: linkerd-ca.deployment.$LINKERD2_PROXY_POD_NAMESPACE.linkerd-managed.kube-system.svc.cluster.local
            - name: LINKERD2_PROXY_TLS_TRUST_ANCHORS
              value: /var/linkerd-io/trust-anchors/trust-anchors.pem
            - name: LINKERD2_PROXY_TLS_CERT
              value: /var/linkerd-io/identity/certificate.crt
            - name: LINKERD2_PROXY_TLS_PRIVATE_KEY
              value: /var/linkerd-io/identity/private-key.p8
            - name: LINKERD2_PROXY_TLS_POD_IDENTITY
              value: linkerd-ca.deployment.$LINKERD2_PROXY_POD_NAMESPACE.linkerd-managed.kube-system.svc.cluster.local
            - name: LINKERD2_PROXY_CONTROLLER_NAMESPACE
              value: kube-system
            - name: LINKERD2_PROXY_TLS_CONTROLLER_IDENTITY
              value: linkerd-controller.deployment.kube-system.linkerd-managed.kube-system.svc.cluster.local
          image: gcr.io/linkerd-io/proxy:stable-2.2.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /metrics
              port: 4191
            initialDelaySeconds: 10
          name: linkerd-proxy
          ports:
            - containerPort: 4143
              name: linkerd-proxy
            - containerPort: 4191
              name: linkerd-metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: 4191
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            runAsUser: 2102
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /var/linkerd-io/trust-anchors
              name: linkerd-trust-anchors
              readOnly: true
            - mountPath: /var/linkerd-io/identity
              name: linkerd-secrets
              readOnly: true
      serviceAccountName: linkerd-ca
      volumes:
        - configMap:
            name: linkerd-ca-bundle
            optional: true
          name: linkerd-trust-anchors
        - name: linkerd-secrets
          secret:
            optional: true
            secretName: linkerd-ca-deployment-tls-linkerd-io