kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-controller
  namespace: kube-system
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-controller-api
  namespace: kube-system
  labels:
    linkerd.io/control-plane-component: controller
  annotations:
    linkerd.io/created-by: linkerd/cli stable-2.2.1
spec:
  type: ClusterIP
  selector:
    linkerd.io/control-plane-component: controller
  ports:
    - name: http
      port: 8085
      targetPort: 8085
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-proxy-api
  namespace: kube-system
  labels:
    linkerd.io/control-plane-component: controller
  annotations:
    linkerd.io/created-by: linkerd/cli stable-2.2.1
spec:
  type: ClusterIP
  selector:
    linkerd.io/control-plane-component: controller
  ports:
    - name: grpc
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    linkerd.io/created-by: linkerd/cli stable-2.2.1
  labels:
    linkerd.io/control-plane-component: controller
  name: linkerd-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      linkerd.io/control-plane-component: controller
  replicas: 3
  template:
    metadata:
      annotations:
        linkerd.io/created-by: linkerd/cli stable-2.2.1
        linkerd.io/proxy-version: stable-2.2.1
      labels:
        linkerd.io/control-plane-component: controller
        linkerd.io/control-plane-ns: kube-system
        linkerd.io/proxy-deployment: linkerd-controller
    spec:
      containers:
        - args:
            - public-api
            - -prometheus-url=http://thanos-query.sys-mon.svc.cluster.local:9090
            - -controller-namespace=kube-system
            - -single-namespace=false
            - -log-level=info
          image: gcr.io/linkerd-io/controller:stable-2.2.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /ping
              port: 9995
            initialDelaySeconds: 10
          name: public-api
          ports:
            - containerPort: 8085
              name: http
            - containerPort: 9995
              name: admin-http
          readinessProbe:
            failureThreshold: 7
            httpGet:
              path: /ready
              port: 9995
          resources:
            requests:
              cpu: 20m
              memory: 50Mi
          securityContext:
            runAsUser: 2103
        - args:
            - proxy-api
            - -addr=:8086
            - -controller-namespace=kube-system
            - -single-namespace=false
            - -enable-tls=true
            - -enable-h2-upgrade=true
            - -log-level=info
          image: gcr.io/linkerd-io/controller:stable-2.2.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /ping
              port: 9996
            initialDelaySeconds: 10
          name: proxy-api
          ports:
            - containerPort: 8086
              name: grpc
            - containerPort: 9996
              name: admin-http
          readinessProbe:
            failureThreshold: 7
            httpGet:
              path: /ready
              port: 9996
          resources:
            requests:
              cpu: 20m
              memory: 50Mi
          securityContext:
            runAsUser: 2103
        - args:
            - tap
            - -controller-namespace=kube-system
            - -single-namespace=false
            - -log-level=info
          image: gcr.io/linkerd-io/controller:stable-2.2.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /ping
              port: 9998
            initialDelaySeconds: 10
          name: tap
          ports:
            - containerPort: 8088
              name: grpc
            - containerPort: 9998
              name: admin-http
          readinessProbe:
            failureThreshold: 7
            httpGet:
              path: /ready
              port: 9998
          resources:
            requests:
              cpu: 20m
              memory: 50Mi
          securityContext:
            runAsUser: 2103
        - env:
            - name: LINKERD2_PROXY_LOG
              value: warn,linkerd2_proxy=info
            - name: LINKERD2_PROXY_CONTROL_URL
              value: tcp://localhost.:8086
            - name: LINKERD2_PROXY_CONTROL_LISTENER
              value: tcp://0.0.0.0:4190
            - name: LINKERD2_PROXY_METRICS_LISTENER
              value: tcp://0.0.0.0:4191
            - name: LINKERD2_PROXY_OUTBOUND_LISTENER
              value: tcp://127.0.0.1:4140
            - name: LINKERD2_PROXY_INBOUND_LISTENER
              value: tcp://0.0.0.0:4143
            - name: LINKERD2_PROXY_DESTINATION_PROFILE_SUFFIXES
              value: .
            - name: LINKERD2_PROXY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LINKERD2_PROXY_INBOUND_ACCEPT_KEEPALIVE
              value: 10000ms
            - name: LINKERD2_PROXY_OUTBOUND_CONNECT_KEEPALIVE
              value: 10000ms
            - name: LINKERD2_PROXY_ID
              value: linkerd-controller.deployment.$LINKERD2_PROXY_POD_NAMESPACE.linkerd-managed.kube-system.svc.cluster.local
            - name: LINKERD2_PROXY_TLS_TRUST_ANCHORS
              value: /var/linkerd-io/trust-anchors/trust-anchors.pem
            - name: LINKERD2_PROXY_TLS_CERT
              value: /var/linkerd-io/identity/certificate.crt
            - name: LINKERD2_PROXY_TLS_PRIVATE_KEY
              value: /var/linkerd-io/identity/private-key.p8
            - name: LINKERD2_PROXY_TLS_POD_IDENTITY
              value: linkerd-controller.deployment.$LINKERD2_PROXY_POD_NAMESPACE.linkerd-managed.kube-system.svc.cluster.local
            - name: LINKERD2_PROXY_CONTROLLER_NAMESPACE
              value: kube-system
            - name: LINKERD2_PROXY_TLS_CONTROLLER_IDENTITY
              value: linkerd-controller.deployment.kube-system.linkerd-managed.kube-system.svc.cluster.local
          image: gcr.io/linkerd-io/proxy:stable-2.2.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /metrics
              port: 4191
            initialDelaySeconds: 10
          name: linkerd-proxy
          ports:
            - containerPort: 4143
              name: linkerd-proxy
            - containerPort: 4191
              name: linkerd-metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: 4191
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            runAsUser: 2102
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /var/linkerd-io/trust-anchors
              name: linkerd-trust-anchors
              readOnly: true
            - mountPath: /var/linkerd-io/identity
              name: linkerd-secrets
              readOnly: true
      serviceAccountName: linkerd-controller
      volumes:
        - configMap:
            name: linkerd-ca-bundle
            optional: true
          name: linkerd-trust-anchors
        - name: linkerd-secrets
          secret:
            optional: true
            secretName: linkerd-controller-deployment-tls-linkerd-io
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceprofiles.linkerd.io
  namespace: kube-system
  annotations:
    linkerd.io/created-by: linkerd/cli stable-2.2.1
spec:
  group: linkerd.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: serviceprofiles
    singular: serviceprofile
    kind: ServiceProfile
    shortNames:
      - sp
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - routes
          properties:
            retryBudget:
              required:
                - minRetriesPerSecond
                - retryRatio
                - ttl
              type: object
              properties:
                minRetriesPerSecond:
                  type: integer
                retryRatio:
                  type: number
                ttl:
                  type: string
            routes:
              type: array
              items:
                type: object
                required:
                  - name
                  - condition
                properties:
                  name:
                    type: string
                  timeout:
                    type: string
                  condition:
                    type: object
                    minProperties: 1
                    properties:
                      method:
                        type: string
                      pathRegex:
                        type: string
                      all:
                        type: array
                        items:
                          type: object
                      any:
                        type: array
                        items:
                          type: object
                      not:
                        type: object
                  responseClasses:
                    type: array
                    items:
                      type: object
                      required:
                        - condition
                      properties:
                        isFailure:
                          type: boolean
                        condition:
                          type: object
                          properties:
                            status:
                              type: object
                              minProperties: 1
                              properties:
                                min:
                                  type: integer
                                  minimum: 100
                                  maximum: 599
                                max:
                                  type: integer
                                  minimum: 100
                                  maximum: 599
                            all:
                              type: array
                              items:
                                type: object
                            any:
                              type: array
                              items:
                                type: object
                            not:
                              type: object